services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ai-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - ai-net
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11500:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - ai-net

volumes:
  ollama:

networks:
  ai-net:
    driver: bridge
